Load data

In [1]:
import pandas as pd

accounts = pd.read_csv(r"C:\Users\HP\Downloads\DA_proj_3\data\accounts.csv")
subscriptions = pd.read_csv(r"C:\Users\HP\Downloads\DA_proj_3\data\subscriptions.csv")
feature_usage = pd.read_csv(r"C:\Users\HP\Downloads\DA_proj_3\data\feature_usage.csv")
support = pd.read_csv(r"C:\Users\HP\Downloads\DA_proj_3\data\support_tickets.csv")
churn = pd.read_csv(r"C:\Users\HP\Downloads\DA_proj_3\data\churn_events.csv")

Basic Inspection

In [2]:
accounts.head()
accounts.info()
accounts.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB

            seats
count  500.000000
mean    20.560000
std     21.044718
min      1.000000
25%      5.000000
50%     15.000000
75%     28.000000
max    163.000000

In [3]:
subscriptions.head()
subscriptions.info()
subscriptions.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB

             seats    mrr_amount     arr_amount
count  5000.000000   5000.000000    5000.000000
mean     29.852000   2267.749400   27212.992800
std      23.089771   3421.375348   41056.504178
min       1.000000      0.000000       0.000000
25%      14.000000    285.000000    3420.000000
50%      24.000000    931.000000   11172.000000
75%      40.000000   2786.000000   33432.000000
max     189.000000  33830.000000  405960.000000

In [4]:
feature_usage.head()
feature_usage.info()
feature_usage.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB

        usage_count  usage_duration_secs   error_count
count  25000.000000         25000.000000  25000.000000
mean      10.021000          3042.202880      0.564280
std        3.143729          2056.544615      1.012595
min        0.000000             0.000000      0.000000
25%        8.000000          1350.000000      0.000000
50%       10.000000          2760.000000      0.000000
75%       12.000000          4400.000000      1.000000
max       26.000000         12696.000000      8.000000

In [5]:
support.head()
support.info()
support.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   object
 1   account_id                   2000 non-null   object
 2   submitted_at                 2000 non-null   object
 3   closed_at                    2000 non-null   object
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB

       resolution_time_hours  first_response_time_minutes  satisfaction_score
count            2000.000000                  2000.000000         1175.000000
mean               35.861000                    88.480000            3.981277
std                21.138427                    51.531877            0.809646
min                 1.000000                     1.000000            3.000000
25%                17.000000                    43.000000            3.000000
50%                35.000000                    88.000000            4.000000
75%                54.000000                   131.000000            5.000000
max                72.000000                   180.000000            5.000000

In [6]:
churn.head()
churn.info()
churn.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB

       refund_amount_usd
count         600.000000
mean           14.420417
std            39.224591
min             0.000000
25%             0.000000
50%             0.000000
75%             0.000000
max           392.920000

In [7]:
#Check for missing values.
accounts.isnull().sum()

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

In [8]:
subscriptions.isnull().sum()

subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

In [9]:
feature_usage.isnull().sum()

usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

In [10]:
support.isnull().sum()

ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

In [11]:
churn.isnull().sum()

churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

Data Type Fixing

In [12]:
subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"])

In [13]:
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"])

In [14]:
churn["churn_date"] = pd.to_datetime(churn["churn_date"])

In [15]:
feature_usage["usage_date"] = pd.to_datetime(feature_usage["usage_date"])

In [16]:
accounts["signup_date"] = pd.to_datetime(accounts["signup_date"])

In [17]:
support["closed_at"] = pd.to_datetime(support["closed_at"])

In [18]:
support["submitted_at"] = pd.to_datetime(support["submitted_at"])

Checking Shape

In [19]:
accounts.shape

(500, 10)

In [20]:
subscriptions.shape

(5000, 14)

In [21]:
feature_usage.shape

(25000, 8)

In [22]:
support.shape

(2000, 9)

In [23]:
churn.shape

(600, 9)

Checking columns

In [24]:
accounts.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag'],
      dtype='object')

In [25]:
subscriptions.columns

Index(['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier',
       'seats', 'mrr_amount', 'arr_amount', 'is_trial', 'upgrade_flag',
       'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag'],
      dtype='object')

In [26]:
feature_usage.columns

Index(['usage_id', 'subscription_id', 'usage_date', 'feature_name',
       'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature'],
      dtype='object')

In [27]:
support.columns

Index(['ticket_id', 'account_id', 'submitted_at', 'closed_at',
       'resolution_time_hours', 'priority', 'first_response_time_minutes',
       'satisfaction_score', 'escalation_flag'],
      dtype='object')

In [28]:
churn.columns

Index(['churn_event_id', 'account_id', 'churn_date', 'reason_code',
       'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'feedback_text'],
      dtype='object')

# Build the Master Analytics Dataset

Merge Accounts + Subscriptions

In [29]:
master_df = accounts.merge(
    subscriptions,
    on="account_id",
    how="left"
)

In [30]:
master_df.shape
master_df.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier_x,seats_x,is_trial_x,churn_flag_x,...,plan_tier_y,seats_y,mrr_amount,arr_amount,is_trial_y,upgrade_flag,downgrade_flag,churn_flag_y,billing_frequency,auto_renew_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Basic,11,209,2508,False,False,False,False,monthly,True
1,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Pro,20,980,11760,False,False,False,False,monthly,True
2,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Pro,9,441,5292,False,False,False,False,monthly,True
3,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Enterprise,9,1791,21492,False,False,False,False,annual,False
4,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Basic,102,1938,23256,False,False,False,False,monthly,True

In [45]:

master_df.shape

(147896, 46)

In [31]:
master_df = master_df.merge(
    feature_usage,
    on="subscription_id",
    how="left"
)

master_df.shape
master_df.head()

Merge Support Tickets

In [32]:
master_df = master_df.merge(
    support,
    on="account_id",
    how="left"
)

Merge Churn Events

In [33]:
master_df = master_df.merge(
    churn,
    on="account_id",
    how="left"
)

In [34]:
master_df.shape
master_df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier_x', 'seats_x', 'is_trial_x',
       'churn_flag_x', 'subscription_id', 'start_date', 'end_date',
       'plan_tier_y', 'seats_y', 'mrr_amount', 'arr_amount', 'is_trial_y',
       'upgrade_flag', 'downgrade_flag', 'churn_flag_y', 'billing_frequency',
       'auto_renew_flag', 'usage_id', 'usage_date', 'feature_name',
       'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature',
       'ticket_id', 'submitted_at', 'closed_at', 'resolution_time_hours',
       'priority', 'first_response_time_minutes', 'satisfaction_score',
       'escalation_flag', 'churn_event_id', 'churn_date', 'reason_code',
       'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'feedback_text'],
      dtype='object')

In [35]:
master_df.shape

(147896, 46)

### Feature Engineering

Aggregate the data by account
- Create Feature Usage Metrics

In [36]:
feature_metrics = master_df.groupby("account_id").agg(
    total_feature_usage=("usage_count", "sum"),
    avg_usage_duration=("usage_duration_secs", "mean"),
    total_errors=("error_count", "sum"),
    beta_feature_usage=("is_beta_feature", "sum")
).reset_index()

Create Support Metrics

In [37]:
support_metrics = master_df.groupby("account_id").agg(
    total_tickets=("ticket_id", "count"),
    avg_resolution_time=("resolution_time_hours", "mean"),
    avg_first_response=("first_response_time_minutes", "mean"),
    avg_satisfaction=("satisfaction_score", "mean"),
    escalation_count=("escalation_flag", "sum")
).reset_index()

Create Revenue Metrics

In [38]:
revenue_metrics = master_df.groupby("account_id").agg(
    total_mrr=("mrr_amount", "sum"),
    total_arr=("arr_amount", "sum")
).reset_index()

Create Subscription Metrics

In [39]:
subscription_metrics = master_df.groupby("account_id").agg(
    plan_type=("plan_tier_y", "first"),
    billing_frequency=("billing_frequency", "first"),
    auto_renew=("auto_renew_flag", "first")
).reset_index()

Customer Information
From accounts table

In [40]:
customer_info = accounts[[
    "account_id",
    "industry",
    "country",
    "seats",
    "is_trial",
    "churn_flag"
]]

#### Final Analytics Dataset

In [41]:
analytics_df = customer_info.merge(feature_metrics, on="account_id", how="left")
analytics_df = analytics_df.merge(support_metrics, on="account_id", how="left")
analytics_df = analytics_df.merge(revenue_metrics, on="account_id", how="left")
analytics_df = analytics_df.merge(subscription_metrics, on="account_id", how="left")

In [42]:
analytics_df.shape
analytics_df.head()

,account_id,industry,country,seats,is_trial,churn_flag,total_feature_usage,avg_usage_duration,total_errors,beta_feature_usage,total_tickets,avg_resolution_time,avg_first_response,avg_satisfaction,escalation_count,total_mrr,total_arr,plan_type,billing_frequency,auto_renew
0,A-2e4581,EdTech,US,9,False,False,2140.0,2769.800000,152.0,16,220,23.000000,91.000000,3.000000,0,196760,2361120,Basic,monthly,True
1,A-43a9e3,FinTech,IN,18,False,True,1065.0,2889.600000,42.0,6,105,38.000000,73.333333,4.000000,0,157209,1886508,Pro,annual,False
2,A-0a282f,DevTools,US,1,False,False,4926.0,3026.626506,288.0,30,498,43.666667,63.666667,4.666667,0,457968,5495616,Pro,annual,True
3,A-1f0ac7,HealthTech,UK,24,True,False,764.0,2500.682927,42.0,10,82,29.000000,174.000000,NaN,0,172004,2064048,Pro,monthly,True
4,A-ce550d,HealthTech,US,35,False,True,4053.0,3720.327586,217.0,28,406,42.285714,107.857143,3.800000,58,2612372,31348464,Enterprise,annual,True

In [46]:
analytics_df.shape

(500, 20)

Export data

In [44]:
analytics_df.to_csv("analytics_dataset.csv", index=False)